[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepFrenchCredsRed"
MatchAction = "Snaffle"
Description = "French credential-related filenames - HIGH PRIORITY"
MatchLocation = "FileName"
WordListType = "Regex"
MatchLength = 0
WordList = ["(?i)mot[\\s_-]*de[\\s_-]*passe",
"(?i)mots[\\s_-]*de[\\s_-]*passe",
"(?i)motdepasse",
"(?i)motsdepasse",
"(?i)identifiants?",
"(?i)acces[\\s_-]+(compt|comptabilite)",
"(?i)acces[\\s_-]+(banq|banque)",
"(?i)acces[\\s_-]+site",
"(?i)acces[\\s_-]+(serv|serveur)",
"(?i)mdp[\\s_-]",
"(?i)[\\s_-]mdp",
"(?i)credential",
"(?i)connexion[\\s_-]",
"(?i)[\\s_-]connexion",
"(?i)confidentiel"]
Triage = "Red"
